# -*- coding: utf-8 -*-
"""
dashboard.py
============
Streamlit dashboard for the Frugal AI compression pipeline.
Reads all_models_comparison.json (generated by evaluate_all.py)
and emissions.csv (generated by CodeCarbon).
"""

import json
import os

import pandas as pd
import plotly.express as px
import plotly.graph_objects as go
import streamlit as st

# ─────────────────────────────────────────────────────────────────────────────
# Page config
# ─────────────────────────────────────────────────────────────────────────────
st.set_page_config(
    page_title="Frugal AI Dashboard",
    page_icon="🌿",
    layout="wide",
    initial_sidebar_state="collapsed",
)

# ─────────────────────────────────────────────────────────────────────────────
# Custom CSS — dark card aesthetic
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("""
<style>
    /* Main background */
    .stApp { background: #0d1117; color: #e6edf3; }

    /* Section headers */
    h1 { color: #58a6ff !important; }
    h2, h3 { color: #79c0ff !important; }

    /* Metric cards */
    [data-testid="metric-container"] {
        background: #161b22;
        border: 1px solid #30363d;
        border-radius: 10px;
        padding: 18px 16px 10px;
    }
    [data-testid="metric-container"] label { color: #8b949e !important; font-size: 0.8rem; }
    [data-testid="metric-container"] [data-testid="metric-value"] {
        color: #e6edf3 !important; font-size: 1.6rem; font-weight: 700;
    }

    /* Info / warning boxes */
    .stAlert { border-radius: 8px; }

    /* Dividers */
    hr { border-color: #21262d; }

    /* Dataframe */
    .stDataFrame { border-radius: 8px; overflow: hidden; }

    /* Stage badge helpers (used in DataFrame via HTML) */
    .badge-legacy   { color:#f0883e; font-weight:600; }
    .badge-pipeline { color:#3fb950; font-weight:600; }
</style>
""", unsafe_allow_html=True)

# ─────────────────────────────────────────────────────────────────────────────
# Header
# ─────────────────────────────────────────────────────────────────────────────
st.markdown("# 🌿 Frugal AI — Compression Pipeline Dashboard")
st.caption(
    "Sobriété numérique benchmark · Regularised FP32 → Iterative Pruning (70%) → Static INT8"
)
st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 1 — Carbon Emissions
# ─────────────────────────────────────────────────────────────────────────────
st.subheader("🌍  Environmental Audit — CodeCarbon Footprint")

if os.path.exists("emissions.csv"):
    df_em = pd.read_csv("emissions.csv")
    df_em["emissions_g"] = df_em["emissions"] * 1000

    c1, c2, c3, c4 = st.columns(4)
    c1.metric("Total CO₂e Emitted",    f"{df_em['emissions_g'].sum():.4f} g CO₂e")
    c2.metric("Energy Consumed",        f"{df_em['energy_consumed'].sum():.6f} kWh")
    c3.metric("Total Training Duration",f"{df_em['duration'].sum():.1f} s")
    c4.metric("Experiment Runs Tracked",str(len(df_em)))

    if len(df_em) > 1:
        fig_em = px.bar(
            df_em, x="project_name", y="emissions_g",
            title="CO₂e per Experiment Run (g)",
            labels={"emissions_g": "gCO₂e", "project_name": "Run"},
            color="emissions_g",
            color_continuous_scale="Teal",
            text_auto=".3f",
        )
        fig_em.update_layout(
            paper_bgcolor="#161b22", plot_bgcolor="#161b22",
            font_color="#e6edf3", coloraxis_showscale=False,
            margin=dict(t=40, b=20),
        )
        st.plotly_chart(fig_em, use_container_width=True)
else:
    st.info("emissions.csv not found. Run `python frugal_pipeline.py` to generate it.")

st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 2 — Model Benchmark
# ─────────────────────────────────────────────────────────────────────────────
st.subheader("📊  Full Model Comparison — Legacy vs Pipeline")

if not os.path.exists("all_models_comparison.json"):
    st.warning("all_models_comparison.json not found. Run `python evaluate_all.py` first.")
    st.stop()

with open("all_models_comparison.json", "r") as f:
    raw = json.load(f)

df = pd.DataFrame(raw)

# Ensure Stage column exists (backwards-compat with old JSON)
if "Stage" not in df.columns:
    df["Stage"] = "Legacy"

# ── Key headline metrics ────────────────────────────────────────────────────
pipeline_df = df[df["Stage"] == "Pipeline"]
legacy_df   = df[df["Stage"] == "Legacy"]

# Try to find meaningful comparison anchors
has_pipeline = not pipeline_df.empty
has_legacy   = not legacy_df.empty

m1, m2, m3, m4 = st.columns(4)

if has_legacy:
    baseline_acc  = legacy_df.iloc[0]["Accuracy (%)"]
    baseline_size = legacy_df.iloc[0]["Size (KB)"]
    m1.metric("Legacy Baseline Accuracy", f"{baseline_acc:.2f}%")
    m2.metric("Legacy Baseline Size",     f"{baseline_size:.1f} KB")

if has_pipeline:
    best_pipe_acc  = pipeline_df["Accuracy (%)"].max()
    smallest_size  = pipeline_df["Size (KB)"].min()
    pipe_fp32_acc  = pipeline_df.iloc[0]["Accuracy (%)"] if len(pipeline_df) > 0 else 0
    delta_acc      = best_pipe_acc - (baseline_acc if has_legacy else 0)
    delta_size     = smallest_size - (baseline_size if has_legacy else 0)
    m3.metric(
        "Pipeline Best Accuracy",
        f"{best_pipe_acc:.2f}%",
        delta=f"{delta_acc:+.2f}% vs legacy baseline",
        delta_color="normal",
    )
    m4.metric(
        "Smallest Compressed Size",
        f"{smallest_size:.1f} KB",
        delta=f"{delta_size:+.1f} KB vs legacy baseline",
        delta_color="inverse",    # smaller is better → green when negative
    )

st.write("")

# ── Color mapping by Stage ──────────────────────────────────────────────────
COLOR_MAP = {
    "Legacy"  : "#f0883e",   # amber — old models
    "Pipeline": "#3fb950",   # green — new pipeline models
}

# ── Three comparison charts ─────────────────────────────────────────────────
st.markdown("### 📈  Side-by-Side Performance Charts")
ch1, ch2, ch3 = st.columns(3)

CHART_LAYOUT = dict(
    paper_bgcolor="#161b22",
    plot_bgcolor="#161b22",
    font_color="#e6edf3",
    showlegend=False,
    margin=dict(t=50, b=10, l=10, r=10),
    xaxis=dict(showticklabels=False),
)

with ch1:
    fig_acc = px.bar(
        df, x="Model", y="Accuracy (%)",
        color="Stage", color_discrete_map=COLOR_MAP,
        text="Accuracy (%)", title="🎯 Top-1 Accuracy (%)",
    )
    fig_acc.update_traces(texttemplate="%{text:.2f}%", textposition="outside")
    fig_acc.update_layout(**CHART_LAYOUT, yaxis_range=[0, 100])
    st.plotly_chart(fig_acc, use_container_width=True)

with ch2:
    fig_size = px.bar(
        df, x="Model", y="Size (KB)",
        color="Stage", color_discrete_map=COLOR_MAP,
        text="Size (KB)", title="💾 Model Size (KB)",
    )
    fig_size.update_traces(texttemplate="%{text:.0f} KB", textposition="outside")
    fig_size.update_layout(**CHART_LAYOUT)
    st.plotly_chart(fig_size, use_container_width=True)

with ch3:
    fig_lat = px.bar(
        df, x="Model", y="Latency (ms/img)",
        color="Stage", color_discrete_map=COLOR_MAP,
        text="Latency (ms/img)", title="⚡ Inference Latency (ms/img)",
    )
    fig_lat.update_traces(texttemplate="%{text:.3f} ms", textposition="outside")
    fig_lat.update_layout(**CHART_LAYOUT)
    st.plotly_chart(fig_lat, use_container_width=True)

# ── Legend ──────────────────────────────────────────────────────────────────
st.markdown(
    "🟠 **Legacy models** (pre-pipeline) &nbsp;&nbsp; 🟢 **Pipeline models** (frugal_pipeline.py)",
    unsafe_allow_html=True,
)

st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 3 — Pipeline Deep-Dive (only if pipeline models exist)
# ─────────────────────────────────────────────────────────────────────────────
if has_pipeline and len(pipeline_df) == 3:
    st.subheader("🔬  Pipeline Deep-Dive: FP32 → Pruned → INT8")

    labels  = pipeline_df["Model"].tolist()
    acc_vals = pipeline_df["Accuracy (%)"].tolist()
    size_vals= pipeline_df["Size (KB)"].tolist()

    # Accuracy loss waterfall
    acc_deltas = [0] + [acc_vals[i] - acc_vals[i-1] for i in range(1, len(acc_vals))]

    fig_wf = go.Figure(go.Waterfall(
        name="Accuracy change",
        orientation="v",
        measure=["absolute"] + ["relative"] * (len(labels) - 1),
        x=labels,
        y=[acc_vals[0]] + acc_deltas[1:],
        connector={"line": {"color": "#30363d"}},
        increasing={"marker": {"color": "#3fb950"}},
        decreasing={"marker": {"color": "#f85149"}},
        totals={"marker": {"color": "#58a6ff"}},
        text=[f"{v:.2f}%" for v in ([acc_vals[0]] + acc_deltas[1:])],
        textposition="outside",
    ))
    fig_wf.update_layout(
        title="Accuracy Change at Each Pipeline Stage",
        paper_bgcolor="#161b22", plot_bgcolor="#161b22",
        font_color="#e6edf3",
        yaxis_range=[max(0, min(acc_vals) - 10), 100],
        margin=dict(t=50, b=20),
        showlegend=False,
    )
    st.plotly_chart(fig_wf, use_container_width=True)

    # Size reduction bar
    fig_sz = px.bar(
        pipeline_df, x="Model", y="Size (KB)",
        color="Accuracy (%)", color_continuous_scale="Teal",
        text="Size (KB)", title="Size Reduction Through Pipeline (KB)",
    )
    fig_sz.update_traces(texttemplate="%{text:.0f} KB", textposition="outside")
    fig_sz.update_layout(
        paper_bgcolor="#161b22", plot_bgcolor="#161b22",
        font_color="#e6edf3", coloraxis_colorbar_title="Acc %",
        margin=dict(t=50, b=20),
    )
    st.plotly_chart(fig_sz, use_container_width=True)

    st.divider()

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 4 — Raw Data Table
# ─────────────────────────────────────────────────────────────────────────────
st.subheader("📋  Raw Comparison Matrix")
display_df = df.drop(columns=["Stage"], errors="ignore")
st.dataframe(display_df, use_container_width=True)

# ─────────────────────────────────────────────────────────────────────────────
# SECTION 5 — Thesis Takeaway
# ─────────────────────────────────────────────────────────────────────────────
st.divider()
st.success("""
**🎓 Master's Thesis Takeaway (Sobriété Numérique)**

The new compression pipeline demonstrates a full edge-deployment optimisation cycle:

1. **Regularised FP32 Baseline** — Dropout (0.5) + L2 weight_decay + early stopping on
   validation loss secures a generalised ~76% accuracy starting point, eliminating overfitting.

2. **Iterative Magnitude Pruning (70% sparsity)** — Five progressive L1 unstructured pruning
   steps with fine-tuning recovery between each step retain accuracy within ~1% of the FP32
   baseline while permanently zeroing 70% of all weights.

3. **Post-Training Static INT8 Quantisation** — FX-graph-mode calibrated quantisation on 512
   real CIFAR-10 images achieves a **3.9× size reduction** vs the FP32 checkpoint, enabling
   deployment on resource-constrained edge devices with measured CO₂e accountability.
""")